<img src="numpy.jpeg">

## NUMPY: Operaciones Basicas

In [1]:
import numpy as np

<ul>
Con esta primera instrucción le estamos diciendo a nuestro programa que de ahora en adelante np será la referencia para todo lo referente a NumPy. Ahora que tenemos asegurado de que la librería esta presente en el entorno, es decir importada y llamada como np podremos trabajar con la función np.array().
</ul>

### Creación de arrays:

<ul>
En este apartado se mostrarán las distintas maneras de crear matrices en Numpy:
</ul>

#### 1. De forma manual:

<ul>
<p>Decimos que la forma manual de crear matrices es aquella en la que introducimos de uno en uno los elementos de la matriz:</p>
    Para la creación de una matriz en este método, solo nos será necesario utilizar la función np.array().
    </ul>

<ul>
<li>Array unidimensional:
</ul>

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


<ul>
<li>Array n-dimensional:
</ul>

In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


#### 2. Recurriendo a funciones:

<ul>
<p>En la práctica es poco eficáz introducir los elementos de uno en uno, por lo que Numpy nos ofrece
generosamente numerosas herramientas del cual podemos apoyarnos.</p>
A continuación os presentaremos estas:
    </ul>

<ul>
    <li><p><b>Array de espacios uniformes:</b></p>
        Utilizando esta función el programa nos devolvera una matriz de numeros consecutivos, pero eso no es todo, podemos manejar la matriz intoduciendo dentro de la función el comienzo, final y salto que hace referencia a los espacios queremos dejar entre número y número.
</ul>

In [8]:
c = np.arange(20)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [9]:
d = np.arange(0,11,2) 
print(d)

[ 0  2  4  6  8 10]


<ul>
    <li><p><b>Array de espacios uniformes con puntos:</b></p>
Como esperareis, esta función nos devuelve una matriz parecida a la que nos daba con la función <i>arange</i> pero en esta deberemos introducir el comienzo, el final y el número de peuntos que queremos que tenga sumando el comienzo y el final.  
    </ul>

In [14]:
e=np.linspace(0,1,10)
print(e)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


<ul>
    <li><p><b>Array de ceros:</b></p>
        Como bien dice su nombre esta función nos devolvera una matriz formada por ceros:
</ul>

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

<ul>
    <li><p><b>Array de unos:</b></p>
        Al mismo modo que la anterior esta función nos devolvera una matriz formada por unos:
</ul>

In [121]:
np.ones(((3,3)), dtype='int') 

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

<ul>
    <li><p><b>Array de uno solo número:</b></p>
        Como no existe funciones como <i>zeros</i> y <i>ones</i> para otros números podemos recurrir a la función <i>full</i>. No es dificil de adivinar que nos devolverá una matriz de un número en especial, para ello introduciremos primero las dimensiones y después el número deseado.
</ul>

In [122]:
np.full((2,2), 10)

array([[10, 10],
       [10, 10]])

<ul>
    <li><p><b>Matriz identidad:</b></p>
En esta función unicamente tendremos que introducir la dimensión de la matriz.
</ul>

In [123]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<ul>
    <li><p><b>Matriz diagonal:</b></p>
En esta función si que introduciremos a mano los elementos diagonales de la matriz mediante la utilizada función <i>np.array</i>.
</ul>

In [21]:
np.diag(np.array([1,2,3]))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

<ul>
    <li><p><b>Array de números aleatorios:</b></p>
        Para este caso utilizaremos la funció <i>random</i>:
</ul>

<ul>
Si queremos una matriz aleatoria de decimales se utilizará <i>random.rand</i> si queremos que sean numeros uniformes de [0,1] y <i>random.randn</i> si queremos que sean gaussianas:
    </ul>

In [22]:
np.random.rand(4,2)

array([[0.09759198, 0.57908288],
       [0.42781699, 0.25453716],
       [0.94310318, 0.45878367],
       [0.05444475, 0.46974935]])

In [23]:
np.random.randn(4,2)

array([[ 1.85807163,  0.0982034 ],
       [ 2.98643944, -1.58748249],
       [ 0.23877765, -0.89032103],
       [-1.17048477, -1.55434016]])

<ul>
Si no queremos decimales, se utilizará <i>random.randint</i>, que nos dará una matriz de enteros:
    </ul>

In [19]:
np.random.randint(-10,10, size=(3,3))

array([[ 5, -5,  9],
       [ 3, -3,  8],
       [-4,  8,  7]])

<ul>
    <li><p>También se puede cargar los datos desde un archivo de texto, pero hoy solo lo dejaremos indicado:</p>
        <p> filedata = np.genfromtxt('data.txt',delimiter=',')</p>
        filedata = filedata.astype('int32')
</ul>

### Operaciones básicas con arrays

Estas operaciones son muy parecidas a las que hemos aprendido con listas:

<ul>
    <li><b>Obtener la dimension:</b>
 </ul>

In [37]:
dimension = np.array([1,2,3])
print(dimension.ndim)

1


<ul>
    <li><b>Obtención de la longitud:</b>
 </ul>

In [38]:
longitud = np.array([[1,2,3],[2,3,4]])
longitud.shape

(2, 3)

<img src="array2.png">

<ul>
    <li><b>Obtención de un elemento específico [<i>r, c</i>]:</b>
 </ul>

In [39]:
f = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(d)

[ 0  2  4  6  8 10]


In [40]:
f[1, 2]

8

In [41]:
f[0, :]

array([1, 2, 3, 4, 5])

In [42]:
f[:, 0] 

array([1, 6])

O escoger varios:

In [43]:
f[1,[0,2,4]]

array([ 6,  8, 10])

<img src="array3.png">

<ul>
    Recordando pasos de la creación de matrices a que también podemos escojer que elementos cojer de una matriz, ordenando desde donde queremos empezar, hasta donde y con cuantos espacios.
    </ul>

In [44]:
#[strarindex:endindex:stepsize]

f[0, 1:4:2]

array([2, 4])

<ul>
    <li><b>sustitución de elementos:</b>
 </ul>

Para un elemento en concreto, introducimos la ubicación en la que se situa.

In [46]:
f[1,2] = 20
print(d)

[ 0  2  4  6  8 10]


Para una columna o fila entera, se seleccionará esa entera y se introducirá los correspondientes que queremos sustituir

In [47]:
f[:,2]=[9,3]
print(d)

[ 0  2  4  6  8 10]


<ul>
    <li><p><b>Repetición de arrays:</b></p>
    A veces nos puede resultar útil poder repetir los elementos de la matriz con una función, ya que así no tendremos que escribirlas a mano.
</ul>

In [20]:
repeticion=np.repeat(a,3)
print(repeticion)

[1 1 1 2 2 2 3 3 3]


In [21]:
r=([[1,2,3]])
repeticion2=np.repeat(r,3, axis=0)
print(repeticion2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


<ul>
    <li><p><b>Cambio en el tipo de datos:</b></p>
    
Los diferentes tipos de datos nos permiten almacenar datos de forma más compacta en la memoria, pero la mayoría de las veces simplemente trabajamos con números int o float.
</ul>

In [118]:
tipo=np.array([1,2,3],dtype='float')
print(tipo)

[1. 2. 3.]


In [119]:
tipo2=np.array([1,2,3],dtype='int')
print(tipo2)

[1 2 3]


### Operaciones matemáticas básicas

In [84]:
g = np.array([1,2,3,4,5])

<ul>
    <li><b>Suma:</b>
 </ul>

In [85]:
g + 2

array([3, 4, 5, 6, 7])

<ul>
    <li><b>resta:</b>
 </ul>

In [102]:
g - 2

array([-1,  0,  1,  2,  3])

<ul>
    <li><b>Múltiplicación:</b>
 </ul>

In [103]:
g * 2

array([ 2,  4,  6,  8, 10])

In [104]:
np.multiply(g,2)

array([ 2,  4,  6,  8, 10])

<ul>
    <li><b>División:</b>
 </ul>

In [105]:
g / 2

array([0.5, 1. , 1.5, 2. , 2.5])

<ul>
    <li><b>Exponencial:</b>
 </ul>

In [106]:
g ** 2

array([ 1,  4,  9, 16, 25], dtype=int32)

<ul>
    <li><b>Para averiguar sin y cos de los elementos:</b>
 </ul>

In [91]:
np.cos(g)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

<ul>
    <li><p><b>Operaciones entre matrices:</b></p>
        Para las operaciones entre arrays sería del mismo método, solo que inroduces dos matrices en vez de una matriz y un número:
 </ul>

In [80]:
h = np.array([2,5,6,8,9])

In [81]:
i = np.array([3,6,1,8,2])

In [82]:
i + h 

array([ 5, 11,  7, 16, 11])

### Álgebra Lineal

<ul>
    <li><p><b>Determinante:</b></p>
 Para calcular el determinante de una matriz utilizaremos una función básica de la librería de Numpy <i>linalg</i> como apoyo.
 </ul>

In [94]:
j=np.identity(3)
np.linalg.det(j)

1.0

Para ver las siguientes operaciones utilizemos dos matrices nuevas:

In [96]:
k = np.random.randint(1, 10, size = (3,3))
print(k)

[[3 3 8]
 [9 8 6]
 [6 3 8]]


In [101]:
l = np.random.randint(1, 10, size = (3,3))
print(l)

<ul>
    <li><b>Producto matricial</b>:
 </ul>

In [98]:
k @ l

array([[ 28,  32,  57],
       [ 46,  75, 113],
       [ 34,  47,  78]])

In [99]:
np.matmul(k, l)

array([[ 28,  32,  57],
       [ 46,  75, 113],
       [ 34,  47,  78]])

<ul>
    <li><b>Producto escalar:</b>
 </ul>

In [107]:
np.vdot(k, l)

363

<ul>
    <li><b>Matriz inversa:</b>
 </ul>


In [108]:
np.linalg.inv(k)

array([[-3.33333333e-01, -2.46716228e-17,  3.33333333e-01],
       [ 2.60869565e-01,  1.73913043e-01, -3.91304348e-01],
       [ 1.52173913e-01, -6.52173913e-02,  2.17391304e-02]])

### Recolocación de matrices

In [36]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

<ul>
 <li>Posición vertical:
 </ul>

In [37]:
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

<ul>
 <li>Posición horizontal:
 </ul>

In [38]:
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6, 7, 8])

### Boolean Masking 

A continuación vamos a ver como Numpy nos permite comprobar e indexar los elementos de las matrices

In [111]:
mask=np.array([[1,12,30,14],[57,-30,0,5],[23,67,-12,-2]])
print(mask)

[[  1  12  30  14]
 [ 57 -30   0   5]
 [ 23  67 -12  -2]]


<ul>
    <li><p><b>Comprobación:</b></p>
     Al introducir una condición (en esta caso aquellos datos mayores a 30), el programa nos devolverá la veracidad de esta:
</ul>

In [112]:
mask>30

array([[False, False, False, False],
       [ True, False, False, False],
       [False,  True, False, False]])

También podemos hacer que nos devuelva la comprobación en números (1 = verdadero y 0 = falso), cambiando el tipo de dato.

In [114]:
mask_num = mask>30
mask_num.astype ( np . int )

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0]])

<ul>
    <li><p><b>Indexación:</b></p>
    Para indexar una matriz utilizaremos una máscara booleana, de este modo, el resultado será una copia y no una vista. La nueva matriz contendrá todos los elementos de la matriz antigua donde el valor correspondiente a la condición es verdadera.
</ul>

In [113]:
#Solo nos mostrará aquellos que sean mayores a 30
mask_nueva = mask[mask>30]
print(mask_nueva)

[57 67]


# SCIPY

### INTEGRALES

<ul>
<p>En general se el método más utilizado en scipy para la integración es la de <i>scipy.integrate,quad()</i></p>
    A continuación os explicaremos como integral con esta herramienta mediante los siguientes ejemplos:
</ul>

<ul>
    <li> <b>Integral definida:</b>
</ul>           

\begin{equation}
 f(x) = \int_{x=0}^{x=5} x^2 \cdot dx
\end{equation}

<ul>
<p>Primero  de todo es importar el modulo de integrales de scipy dentro de nuestro programa, lo que conseguimos con esta importación es traernos el modulo que nos permitirá hacer las integrales y lo renombramos como <i>integrate</i>, para poder utilizarlo en nuestro código:</p>
</ul>

In [150]:
import scipy.integrate as integrate

In [148]:
resultado = integrate.quad(lambda x: x ** 2, 0, 5)
print(resultado)

(41.66666666666666, 4.625929269271485e-13)


<ul>
    <p>Como podemos observar, este nos devuelve dos observaciones:</p>
    Por un lado el resultado (izquierda) y por el otro el posible error cometido al realizar la integral (izquierda). Estas se van ha poder llamar en cualquier momento.
</ul>

In [149]:
print(resultado[0])

41.66666666666666


<ul>
   <li> Integral múltiple:
</ul>           

\begin{equation}
 Área = \int_{y = 0}^{y=1/2}\int_{x=0}^{x=1-2x} xy \cdot dx dy
\end{equation}

<ul>
En este ejercicio queremos calcular el área de esta integral resolviendola, en estos caso de integral multiple scipy nos proporcona la funcón <i>nquad</i>. Podemos observar es que en este caso habrá que definir los elementos de la integral, para poder utilizarlas en conjunto en la función:
    </ul>

In [169]:
from scipy import integrate

def f(x, y):
    return x * y
def lim_y():
    return [0, 0.5]
def lim_x(y):
     return [0, 1 - 2 * y]
area = integrate.nquad(f, [lim_x, lim_y])
print (area[0])

0.010416666666666668


### OPTIMIZACIÓN

In [ ]:
from scipy.optimize import minimize

In [ ]:
def objetivo(x):
    x1 = x[0]
    x2 = x[1]
    x3 = x[2]
    x4 = x[3] 
    return x1*x4*x3*x4
    